{{- if .Values.argocd.giropopsSenhas.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
        - name: 'giropopsSenhas.replicas'
          value: '{{ .Values.argocd.giropopsSenhas.replicas }}'
    repoURL: 'https://github.com/SamiraCavalcanti/descomplicando-gitops-no-kubernetes-argocd-linuxtips.git'
    targetRevision: feat/day2
    path: giropops-senhas/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: giropops-senhas
  syncPolicy: 
    automated: {
      selfHeal: true
    }
    syncOptions:
      - CreateNamespace=true

{{- end }}
