apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: SamiraCavalcanti
        repo: descomplicando-gitops-no-kubernetes-argocd-linuxtips
        tokenRef:
          secretName: secret-token-github
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'stack-apps-{{.branch_slug}}-{{.number}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SamiraCavalcanti/descomplicando-gitops-no-kubernetes-argocd-linuxtips.git
        targetRevision: '{{.head_sha}}'
        path: app-of-apps/
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-of-apps-{{.branch_slug}}-{{.number}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true